### ISSUE TITLE
License identifier not matched correctly

### ISSUE THREAD

**Issue by rmfranken** [sdsc-ordes/gimie#100]
Scancode's license matcher does not return a spdx identifier by default. We currently convert the "license expression" found by normalizing the string, and then looking up that match in the big static scancode license dictionary file. Problem is that the found match does not always have a key in that dictionary. 

Example:
The license text belonging to the spdx identifier https://spdx.org/licenses/BSD-3-Clause.html is found by scancode api as "bsd-new". See scancode output below

```
[{'license_expression': 'bsd-new', 'matches': [{'score': 99.53, 'start_line': 3, 'end_line': 8, 'matched_length': 210, 'match_coverage': 100.0, 'matcher': '2-aho', 'license_expression': 'bsd-new', 'rule_identifier': 'bsd-new_31.RULE', 'rule_relevance': 100, 'rule_url': 'https://github.com/nexB/scancode-toolkit/tree/develop/src/licensedcode/data/rules/bsd-new_31.RULE', ... , 'identifier': 'bsd_new-b02c5829-769b-deef-d8c8-55549a5900e9'}]
```

"bsd-new", even when normalized, does not appear in the scancode dictionary of licenses. This is not a super common thing, but it's not very rare either, see the large number of inconsistencies [here ](https://scancode-licensedb.aboutcode.org/index.html).

Found by running `gimie data https://github.com/MouseLand/cellpose/`

**Comment by cmdoret** [comment]
As we are currently switching to a different license matcher, this is probably not something we want to fix in gimie.
It is good to keep this in mind however, especially if we later decide to use scancode to build a "ground truth" to improve our own matcher.
