### ISSUE TITLE
Use CFF file as a source for DOI and authors+ORCID

### ISSUE THREAD

**Issue by rmfranken** [sdsc-ordes/gimie#53]
As [CFF ](https://citation-file-format.github.io/)(citation file format) is a best practice recommended by fair-software.eu, we should aim to use this meta-data captured in a CFF file to further enhance Gimie output. For instance, extracting DOI (into schema:identifier).

**Note:** Depends on #97 

**Objective:** Add parser for CFF files to extract DOI

**Requirements:**

+ [ ] New `gimie.parsers.CffParser` follows the `gimie.parsers.Parser` interface
+ [ ]  is added to `gimie.parsers.PARSERS`
+ [ ] Tests verify that parser works as expected.

**Next steps:**
* Discuss if other properties should be extracted 's  (e.g. authors  in some properties such as m4di:orcidId , schema:author)

**Comment by rmfranken** [comment]
Not really gimie's domain - we can get the information associated with a DOI using different services. Gimie is for repositories, not for publications.

**Comment by cmdoret** [comment]
closed by #107
